services:
  mysql:
    image: mysql:8.0.39
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d
        read_only: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
  redis:
    image: redis:7.4.0
    restart: "no"
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  rabbitmq:
    image: rabbitmq:3.13.6
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  mongo:
    image: mongo:7.0.14
    restart: "no"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db
volumes:
  mysql_data:
  mongo_data: